"use client";

/**
 * ============================================================================
 * STANDALONE GIT PROJECT EXPORTER (NEXT.JS 15 & REACT 19 REPOSITORY PACKAGER)
 * ============================================================================
 * Compiles visual AST models, database schemas, API routes, logic blueprints,
 * animations, and styles into a production-grade, independently bootable
 * Next.js 15 App Router repository with zero manual fixes needed.
 * Architecture Ref: ROADMAP.md §Sub-Phase 6.4 & Detailed Roadmap Phase 22
 * ============================================================================
 */

import { EmittedFile, TargetFramework } from "../../core/types/compiler";
import { ProjectElement, PageDefinition } from "../../core/store/useProjectStore";
import { CollectionSchema } from "../../core/types/database";
import { BlueprintGraph } from "../../core/ast/ASTManager";
import { AnimationSample } from "../../core/types/animations";
import { ThemeConfig } from "../../core/types/theme";
import { ReactComponentEmitter } from "../emitters/ReactComponentEmitter";
import { StyleEmitter } from "../emitters/StyleEmitter";
import { GSAPAnimationEmitter } from "../emitters/GSAPAnimationEmitter";
import { PrismaSchemaEmitter } from "../emitters/PrismaSchemaEmitter";
import { ApiRouteEmitter } from "../emitters/ApiRouteEmitter";
import { LogicFlowEmitter } from "../emitters/LogicFlowEmitter";
import { ZipPacker } from "./ZipPacker";

export interface GitExporterOptions {
  /** Application package name (default: "webgen-app") */
  projectName?: string;
  /** Human-readable application description */
  description?: string;
  /** Semantic version string (default: "0.1.0") */
  version?: string;
  /** Target package manager for instructions and scripts (default: "npm") */
  packageManager?: "npm" | "pnpm" | "yarn";
  /** Project layout architecture (default: "standalone") */
  structure?: "standalone" | "monorepo";
  /** Target framework version (default: "nextjs15") */
  targetFramework?: TargetFramework;
  /** Whether to scaffold Prisma database configuration */
  includePrisma?: boolean;
  /** Whether to scaffold GSAP animation hooks */
  includeAnimations?: boolean;
  /** Whether to scaffold GitHub Actions CI workflow (default: true) */
  includeCI?: boolean;
  /** Package author identifier */
  author?: string;
}

export interface ExportManifest {
  projectName: string;
  version: string;
  targetFramework: string;
  totalFiles: number;
  totalBytes: number;
  createdAt: string;
  fileList: string[];
  categories: Record<string, number>;
}

export interface ExportBundle {
  files: EmittedFile[];
  manifest: ExportManifest;
  getFile(path: string): EmittedFile | undefined;
  toZip(): ZipPacker;
  toZipBuffer(): Uint8Array;
  toZipBlob(): Blob;
  downloadZip(filename?: string): void;
}

export interface ProjectExportInput {
  pages: Record<string, PageDefinition>;
  elements: Record<string, ProjectElement>;
  databaseSchemas?: Record<string, CollectionSchema>;
  blueprintGraphs?: Record<string, BlueprintGraph>;
  animationSamples?: Record<string, AnimationSample>;
  themeConfig?: ThemeConfig;
}

export class GitExporter {
  /**
   * Generates a complete package.json for the exported Next.js 15 repository.
   */
  public static generatePackageJson(
    options: GitExporterOptions = {},
    hasPrisma: boolean = false,
    hasGsap: boolean = false
  ): string {
    const name = (options.projectName || "webgen-app")
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, "-");

    const dependencies: Record<string, string> = {
      next: "^15.0.0",
      react: "^19.0.0",
      "react-dom": "^19.0.0",
      "lucide-react": "^1.41.0",
    };

    if (hasGsap) {
      dependencies["gsap"] = "^3.15.0";
    }

    if (hasPrisma) {
      dependencies["@prisma/client"] = "^5.20.0";
    }

    const devDependencies: Record<string, string> = {
      typescript: "^5.6.0",
      "@types/node": "^20.14.0",
      "@types/react": "^19.0.0",
      "@types/react-dom": "^19.0.0",
      eslint: "^9.0.0",
      "eslint-config-next": "15.0.0",
    };

    if (hasPrisma) {
      devDependencies["prisma"] = "^5.20.0";
    }

    const scripts: Record<string, string> = {
      dev: "next dev",
      build: "next build",
      start: "next start",
      lint: "next lint",
    };

    if (hasPrisma) {
      scripts["prisma:generate"] = "prisma generate";
      scripts["db:push"] = "prisma db push";
      scripts["db:migrate"] = "prisma migrate dev";
    }

    const pkg = {
      name,
      version: options.version || "0.1.0",
      description: options.description || "Production Next.js 15 web application generated by WebAPPBuilder",
      private: true,
      author: options.author || "WebAPPBuilder Visual Studio",
      scripts,
      dependencies,
      devDependencies,
    };

    return JSON.stringify(pkg, null, 2) + "\n";
  }

  /**
   * Generates standard Next.js tsconfig.json.
   */
  public static generateTsConfig(): string {
    const config = {
      compilerOptions: {
        target: "ES2022",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [
          {
            name: "next",
          },
        ],
        paths: {
          "@/*": ["./*"],
        },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    };

    return JSON.stringify(config, null, 2) + "\n";
  }

  /**
   * Generates Next.js configuration (next.config.ts).
   */
  public static generateNextConfig(): string {
    return [
      'import type { NextConfig } from "next";',
      "",
      "const nextConfig: NextConfig = {",
      "  reactStrictMode: true,",
      "  poweredByHeader: false,",
      "  experimental: {",
      "    // App Router optimisations",
      "  },",
      "};",
      "",
      "export default nextConfig;",
      "",
    ].join("\n");
  }

  /**
   * Generates Next.js TypeScript environment declarations (next-env.d.ts).
   */
  public static generateNextEnv(): string {
    return [
      '/// <reference types="next" />',
      '/// <reference types="next/image-types/global" />',
      "",
      "// NOTE: This file should not be edited",
      "// see https://nextjs.org/docs/app/api-reference/config/typescript for more information.",
      "",
    ].join("\n");
  }

  /**
   * Generates standard .gitignore file.
   */
  public static generateGitIgnore(): string {
    return [
      "# dependencies",
      "/node_modules",
      "/.pnp",
      ".pnp.js",
      "",
      "# testing",
      "/coverage",
      "",
      "# next.js",
      "/.next/",
      "/out/",
      "",
      "# production",
      "/build",
      "",
      "# misc",
      ".DS_Store",
      "*.pem",
      "",
      "# debug logs",
      "npm-debug.log*",
      "yarn-debug.log*",
      "yarn-error.log*",
      "",
      "# local env files",
      ".env*.local",
      ".env",
      "",
      "# vercel",
      ".vercel",
      "",
      "# typescript",
      "*.tsbuildinfo",
      "",
    ].join("\n");
  }

  /**
   * Generates sample environment variables (.env.example).
   */
  public static generateEnvExample(hasPrisma: boolean = false): string {
    const lines = [
      "# ============================================================================",
      "# ENVIRONMENT CONFIGURATION EXAMPLE",
      "# ============================================================================",
      "# Copy this file to .env and configure your values.",
      "",
      'NEXT_PUBLIC_APP_URL="http://localhost:3000"',
    ];

    if (hasPrisma) {
      lines.push("");
      lines.push("# Prisma Database Connection URL");
      lines.push('# Example PostgreSQL: postgresql://postgres:password@localhost:5432/webapp?schema=public');
      lines.push('# Example SQLite: file:./dev.db');
      lines.push('DATABASE_URL="postgresql://postgres:password@localhost:5432/webapp?schema=public"');
    }

    lines.push("");
    return lines.join("\n");
  }

  /**
   * Generates a production README.md with setup instructions and architecture documentation.
   */
  public static generateReadme(
    projectName: string,
    pages: PageDefinition[] = [],
    schemas: CollectionSchema[] = [],
    graphs: BlueprintGraph[] = []
  ): string {
    const lines = [
      `# ${projectName}`,
      "",
      "Production Next.js 15 & React 19 web application compiled and exported from **WebAPPBuilder Visual Studio**.",
      "",
      "## 🚀 Quick Start",
      "",
      "### 1. Install Dependencies",
      "```bash",
      "npm install",
      "# or pnpm install / yarn install",
      "```",
      "",
      "### 2. Configure Environment Variables",
      "```bash",
      "cp .env.example .env",
      "```",
    ];

    if (schemas.length > 0) {
      lines.push("");
      lines.push("### 3. Initialize Prisma Database");
      lines.push("```bash", "npx prisma db push", "npx prisma generate", "```");
    }

    lines.push(
      "",
      `### ${schemas.length > 0 ? "4" : "3"}. Run Development Server`,
      "```bash",
      "npm run dev",
      "```",
      "",
      "Open [http://localhost:3000](http://localhost:3000) with your browser to see the result.",
      "",
      "---",
      "",
      "## 📁 Project Architecture",
      "",
      "```",
      "├── app/",
      "│   ├── layout.tsx         # Root layout & HTML shell",
      "│   ├── globals.css        # Visual design tokens & CSS variables",
      "│   ├── page.tsx           # Home landing page",
    );

    for (const p of pages) {
      if (p.slug !== "/") {
        const slugClean = p.slug.replace(/^\//, "");
        lines.push(`│   ├── ${slugClean}/page.tsx   # ${p.name} page`);
      }
    }

    if (schemas.length > 0) {
      lines.push(
        "│   └── api/               # Next.js App Router API Handlers",
        "│       └── [collection]/  # Generic & custom collection CRUD endpoints",
      );
    }

    lines.push(
      "├── components/            # Reusable typed React 19 UI components",
      "├── styles/                # Scoped CSS stylesheets & design tokens",
    );

    if (graphs.length > 0) {
      lines.push("├── server/logic/          # Compiled async TypeScript logic blueprints");
    }

    if (schemas.length > 0) {
      lines.push(
        "├── prisma/                # Prisma ORM schema & SQL migrations",
        "│   ├── schema.prisma",
        "│   └── migrations/",
        "└── lib/",
        "    └── prisma.ts          # Singleton Prisma client instance",
      );
    }

    lines.push(
      "├── .github/workflows/     # CI/CD Automated Build & Lint workflow",
      "└── package.json           # Dependencies & scripts",
      "```",
      "",
      "---",
      "",
      "## 🛠 Available Scripts",
      "",
      "- `npm run dev` — Starts Next.js development server with hot reload",
      "- `npm run build` — Builds the production-optimized application",
      "- `npm run start` — Starts the production Next.js server",
      "- `npm run lint` — Runs ESLint checks across all TypeScript files",
    );

    if (schemas.length > 0) {
      lines.push(
        "- `npm run prisma:generate` — Regenerates Prisma Client types",
        "- `npm run db:push` — Pushes database schema directly without migrations",
        "- `npm run db:migrate` — Creates and applies SQL migrations",
      );
    }

    lines.push("");
    return lines.join("\n");
  }

  /**
   * Generates the root Next.js App Router layout (app/layout.tsx).
   */
  public static generateRootLayout(projectName: string = "WebAPPBuilder Application"): string {
    return [
      'import React from "react";',
      'import type { Metadata } from "next";',
      'import "./globals.css";',
      "",
      "export const metadata: Metadata = {",
      `  title: "${projectName}",`,
      `  description: "Generated by WebAPPBuilder Visual Studio & Blueprint Compiler",`,
      "};",
      "",
      "export default function RootLayout({",
      "  children,",
      "}: {",
      "  children: React.ReactNode;",
      "}) {",
      "  return (",
      '    <html lang="en">',
      "      <body>",
      "        {children}",
      "      </body>",
      "    </html>",
      "  );",
      "}",
      "",
    ].join("\n");
  }

  /**
   * Generates the Prisma Client singleton helper (lib/prisma.ts) for Next.js.
   */
  public static generatePrismaClientSingleton(): string {
    return [
      'import { PrismaClient } from "@prisma/client";',
      "",
      "const globalForPrisma = globalThis as unknown as {",
      "  prisma: PrismaClient | undefined;",
      "};",
      "",
      "export const prisma =",
      "  globalForPrisma.prisma ??",
      "  new PrismaClient({",
      '    log: process.env.NODE_ENV === "development" ? ["query", "error", "warn"] : ["error"],',
      "  });",
      "",
      'if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;',
      "",
    ].join("\n");
  }

  /**
   * Generates the GitHub Actions automated CI workflow (.github/workflows/ci.yml).
   */
  public static generateGitHubActionsWorkflow(): string {
    return [
      "name: Next.js CI",
      "",
      "on:",
      "  push:",
      "    branches: [main, master]",
      "  pull_request:",
      "    branches: [main, master]",
      "",
      "jobs:",
      "  build-and-test:",
      "    runs-on: ubuntu-latest",
      "",
      "    steps:",
      "      - name: Checkout repository",
      "        uses: actions/checkout@v4",
      "",
      "      - name: Set up Node.js 20",
      "        uses: actions/setup-node@v4",
      "        with:",
      "          node-version: 20",
      "          cache: 'npm'",
      "",
      "      - name: Install dependencies",
      "        run: npm ci || npm install",
      "",
      "      - name: Run TypeScript typecheck",
      "        run: npx tsc --noEmit",
      "",
      "      - name: Build Next.js project",
      "        run: npm run build",
      "        env:",
      "          SKIP_ENV_VALIDATION: 'true'",
      "",
    ].join("\n");
  }

  /**
   * Packages the visual project state into a complete, standalone, bootable Next.js repository bundle.
   */
  public static packageProject(
    input: ProjectExportInput,
    options: GitExporterOptions = {}
  ): ExportBundle {
    const files: EmittedFile[] = [];
    const projectName = options.projectName || "WebGen App";
    const pagesList = Object.values(input.pages || {});
    const schemasList = Object.values(input.databaseSchemas || {});
    const graphsList = Object.values(input.blueprintGraphs || {});
    const animationsList = Object.values(input.animationSamples || {});
    const hasPrisma = options.includePrisma !== false && schemasList.length > 0;
    const hasGsap = options.includeAnimations !== false && animationsList.length > 0;

    // 1. Root Scaffolding Configuration
    files.push({
      path: "package.json",
      content: GitExporter.generatePackageJson(options, hasPrisma, hasGsap),
      language: "json",
      type: "page",
    });

    files.push({
      path: "tsconfig.json",
      content: GitExporter.generateTsConfig(),
      language: "json",
      type: "page",
    });

    files.push({
      path: "next.config.ts",
      content: GitExporter.generateNextConfig(),
      language: "typescript",
      type: "page",
    });

    files.push({
      path: "next-env.d.ts",
      content: GitExporter.generateNextEnv(),
      language: "typescript",
      type: "page",
    });

    files.push({
      path: ".gitignore",
      content: GitExporter.generateGitIgnore(),
      language: "typescript",
      type: "page",
    });

    files.push({
      path: ".env.example",
      content: GitExporter.generateEnvExample(hasPrisma),
      language: "typescript",
      type: "page",
    });

    files.push({
      path: "README.md",
      content: GitExporter.generateReadme(projectName, pagesList, schemasList, graphsList),
      language: "typescript",
      type: "page",
    });

    if (options.includeCI !== false) {
      files.push({
        path: ".github/workflows/ci.yml",
        content: GitExporter.generateGitHubActionsWorkflow(),
        language: "typescript",
        type: "page",
      });
    }

    // 2. App Router Layout & Globals
    files.push({
      path: "app/layout.tsx",
      content: GitExporter.generateRootLayout(projectName),
      language: "typescript",
      type: "page",
    });

    // Design Tokens & Styles
    const tokenFile = StyleEmitter.emitTokens(input.themeConfig || {
      colors: {
        canvasBg: "#0F172A",
        accentPrimary: "#206859",
        textPrimary: "#F8FAFC",
        borderDefault: "#334155",
      },
      wires: {
        exec: "#FFFFFF",
        string: "#F59E0B",
        number: "#10B981",
        boolean: "#EF4444",
      },
    });
    files.push({
      path: "app/globals.css",
      content: tokenFile.content,
      language: "css",
      type: "styles",
    });

    if (input.elements && Object.keys(input.elements).length > 0) {
      const stylesFile = StyleEmitter.emitProjectStyles(input.elements);
      files.push({
        path: "app/page.css",
        content: stylesFile.content,
        language: "css",
        type: "styles",
      });
    }

    // 3. Pages & Key Components
    for (const page of pagesList) {
      if (page.rootElementId && input.elements[page.rootElementId]) {
        files.push(ReactComponentEmitter.emitPage(page, input.elements));
      }
    }

    // Custom Components
    for (const el of Object.values(input.elements || {})) {
      if (el.parentId === null && el.children && el.children.length > 0) {
        files.push(ReactComponentEmitter.emitComponent(el.id, input.elements));
      }
    }

    // 4. Animation Hooks (GSAP)
    if (hasGsap) {
      for (const sample of animationsList) {
        files.push(GSAPAnimationEmitter.emitHook(sample));
      }
    }

    // 5. Database & Prisma Scaffolding
    if (hasPrisma && input.databaseSchemas) {
      files.push(PrismaSchemaEmitter.emitSchema(input.databaseSchemas));
      files.push(PrismaSchemaEmitter.emitSqlMigration(input.databaseSchemas));
      files.push({
        path: "lib/prisma.ts",
        content: GitExporter.generatePrismaClientSingleton(),
        language: "typescript",
        type: "schema",
      });

      // REST API Routes
      for (const schema of schemasList) {
        files.push(ApiRouteEmitter.emitCollectionRoute(schema));
        files.push(ApiRouteEmitter.emitItemRoute(schema));
      }
    }

    // 6. Logic Blueprint Flows
    for (const graph of graphsList) {
      files.push(LogicFlowEmitter.emitLogicFlow(graph));
    }

    // Build Export Manifest
    const fileList = files.map((f) => f.path);
    let totalBytes = 0;
    const categories: Record<string, number> = {};

    for (const f of files) {
      const bytes = new TextEncoder().encode(f.content).length;
      totalBytes += bytes;
      categories[f.type] = (categories[f.type] || 0) + 1;
    }

    const manifest: ExportManifest = {
      projectName,
      version: options.version || "0.1.0",
      targetFramework: options.targetFramework || "nextjs15",
      totalFiles: files.length,
      totalBytes,
      createdAt: new Date().toISOString(),
      fileList,
      categories,
    };

    // Add manifest as a file in the bundle
    files.push({
      path: "export-manifest.json",
      content: JSON.stringify(manifest, null, 2) + "\n",
      language: "json",
      type: "page",
    });

    const bundle: ExportBundle = {
      files,
      manifest,
      getFile(path: string): EmittedFile | undefined {
        return files.find((f) => f.path === path);
      },
      toZip(): ZipPacker {
        const packer = new ZipPacker();
        for (const file of files) {
          packer.addFile(file.path, file.content);
        }
        return packer;
      },
      toZipBuffer(): Uint8Array {
        return this.toZip().build();
      },
      toZipBlob(): Blob {
        return this.toZip().toBlob();
      },
      downloadZip(filename: string = `${projectName.toLowerCase().replace(/[^a-z0-9-]/g, "-")}-nextjs.zip`): void {
        this.toZip().download(filename);
      },
    };

    return bundle;
  }
}
